In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('cars.csv')

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
'''
now, we have all the categorical variables which are only nominal, and hence, we do one hot encoding.
first of all, we check the frequency dist of each column, in order to see if we can use ohe  with most frequent variables.
'''

'\nnow, we have all the categorical variables which are only nominal, and hence, we do one hot encoding. \nfirst of all, we check the frequency dist of each column, in order to see if we can use ohe  with most frequent variables. \n'

In [ ]:
'''
below, we can see that there 32 unique brands in the dataset. if we do ohe considering each brand, we will have n-1 columns after dropping
dummy variable and that will be 31 columns. the dimensionality of the dataset will increase exponentially. we don't want that. hence
we keep only 10 most frequent brands here, keep other brands in 'others' category.
'''
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()

32

In [ ]:
#just 4 values, keeping them all
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [ ]:
#just 5 values, keeping them all
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
'''
firstly, doing for fuel and owner, altogther as they have less unique values.
'''

'\nfirstly, doing for fuel and owner, altogther as they have less unique values.\n'

### Using pandas for OHE

In [ ]:
tempdf = pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
'''
drop first removes the first column (being the dummy variable) for fuel and for owner, so in total, 2 columns got removed.
'''

'\ndrop first removes the first column (being the dummy variable) for fuel and for owner, so in total, 2 columns got removed. \n'

In [ ]:
tempdf

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [ ]:
bool_cols = tempdf.select_dtypes('bool').columns
tempdf[bool_cols] = tempdf[bool_cols].astype(int)

In [ ]:
tempdf

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [ ]:
freq = df['brand'].value_counts()
threshold = 100

In [ ]:
type(freq)
'''
so it is a pandas series that we got with the brand names being index.
'''

'\nso it is a pandas series that we got with the brand names being index. \n'

In [ ]:
freq_threshold = freq[freq<=threshold]

In [ ]:
freq_threshold
'''
so this is an updated series having only those brands where count <= 100. we will put all these brands in the 'other' category.
'''

"\nso this is an updated series having only those brands where count <= 100. we will put all these brands in the 'other' category. \n"

In [ ]:
replace_index = freq_threshold.index
replace_index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [ ]:
tempdf= df['brand'].replace(replace_index,'others')

In [ ]:
tempdf1= pd.get_dummies(df , columns = ['brand'], drop_first=True)

In [ ]:
tempdf1

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
0,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
bool_cols = tempdf1.select_dtypes('bool').columns
tempdf1[bool_cols] = tempdf1[bool_cols].astype(int)
tempdf1

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,1,0,0,0

### Why get into all this fuss? Simply use column transformer:-

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(drop='first'),['fuel','owner','brand'])
],remainder='passthrough')

In [ ]:
df= pd.read_csv('cars.csv')
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['selling_price', 'km_driven']),df['selling_price'],
                                                test_size=0.2)

In [ ]:
X_train

          brand    fuel         owner
1412     Toyota  Diesel   Third Owner
3199  Chevrolet  Diesel   First Owner
5819    Hyundai  Petrol   First Owner
299     Hyundai  Petrol   First Owner
6542       Ford  Diesel   First Owner
...         ...     ...           ...
594      Maruti  Petrol   First Owner
3093        BMW  Diesel   First Owner
2134      Honda  Petrol  Second Owner
408      Maruti  Petrol  Second Owner
456       Honda  Diesel   First Owner

[6502 rows x 3 columns]

In [ ]:
X_train['brand']= X_train['brand'].replace(freq_threshold.index,'others')
X_train['brand'].value_counts()

brand
Maruti        1952
Hyundai       1127
Mahindra       614
Tata           570
others         441
Toyota         393
Honda          376
Ford           312
Chevrolet      187
Renault        186
Volkswagen     157
BMW             97
Skoda           90
Name: count, dtype: int64

In [ ]:
transformer.fit_transform(X_train).shape

(6502, 19)

In [ ]:
X_test['brand']= X_test['brand'].replace(freq_threshold.index,'others')
X_test['brand'].value_counts()

brand
Maruti        496
Hyundai       288
Tata          164
Mahindra      158
others         97
Toyota         95
Honda          91
Ford           85
Chevrolet      43
Renault        42
Volkswagen     29
BMW            23
Skoda          15
Name: count, dtype: int64

In [ ]:
transformer.transform(X_test).shape

(1626, 19)