### STEPS FOR ASSESSING THE DATA:-

### 1. Write data summary which gives a gist of the whole dataset:-
This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra (a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of insulin before. All were experiencing elevated HbA1c levels.

All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks, which isnâ€™t enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra:

- 175 patients switched to Auralin for 24 weeks
- 175 patients continued using Novodra for 24 weeks
Data about patients feeling some adverse effects is also recorded.

### 2. Write the description of column so that the analyser has thorough idea what each column/variable represents

#### **Table** -> `patients`:

- `patient_id`: the unique identifier for each patient in the Master Patient Index (i.e. patient database) of the pharmaceutical company that is producing Auralin
- `assigned_sex`: the assigned sex of each patient at birth (male or female)
- `given_name`: the given name (i.e. first name) of each patient
- `surname`: the surname (i.e. last name) of each patient
- `address`: the main address for each patient
- `city`: the corresponding city for the main address of each patient
- `state`: the corresponding state for the main address of each patient
- `zip_code`: the corresponding zip code for the main address of each patient
- `country`: the corresponding country for the main address of each patient (all United states for this clinical trial)
- `contact`: phone number and email information for each patient
- `birthdate`: the date of birth of each patient (month/day/year). The inclusion criteria for this clinical trial is age >= 18 (there is no maximum age because diabetes is a growing problem among the elderly population)
- `weight`: the weight of each patient in pounds (lbs)
- `height`: the height of each patient in inches (in)
- `bmi`: the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.


#### **Table** -> `treatments` and `treatment_cut`:

- `given_name`: the given name of each patient in the Master Patient Index that took part in the clinical trial
- `surname`: the surname of each patient in the Master Patient Index that took part in the clinical trial
- `auralin`: the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.
- `novodra`: same as above, except for patients that continued treatment with Novodra
- `hba1c_start`: the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
- `hba1c_end`: the patient's HbA1c level at the end of the last week of treatment
- `hba1c_change`: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start - hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

#### **Table** -> `adverse_reactions`

- `given_name`: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `surname`: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `adverse_reaction`: the adverse reaction reported by the patient

In [36]:
'''
assessment = finding out errors from the data.
cleaning = eradicating those errors.

there are 2 types of assessments:-
1. manual = you just go through the excel of the dataset, and try to "look" with your naked eyes for any flaws within the dataset

2. automatic = using python built in functions to find the errors in the dataset.

Doing assessment with all the 4 tables:-

i) DIRTY DATA

table 1:- Patients

manual:- (what inconsistencies I saw with my eyes)
-patient with id=9, the name is misspelled as Dsvid whereas in the contact mail, it's David (accuracy)
-In the state column, it sometimes has full form, as New York, and sometimes the abbreviated form being NY denoting the same. (consistency)
-Zip code of few addresses being 4 digit no, whereas by rule, it should be 5 digit no. (validity)

automatic:-
when I used .info() built in function:-
-few col had non null values which were lesser than the rest. it means, there are missing values in this column. data missing for 12 patients
in address,city, state,zip_code ,country, contact. (completeness)
-.info() also shows the dtype:-
sex = obj (string as in male/female) but it uses more memory. instead you can one hot encode to 0 and 1. (validity)
zip code = float, should have been int (validity)
birthdate = obj, should have been datetime (validity)
-dwhen using .duplicated() , duplicate entries by the name John Doe (validity)
-when using .describe(), it does mathematical calculations. from the result, min height = 27 inches which ain't possible for high bmi. one has
weight of 48 pounds as 5.2ft height which ain't possible. (accuracy)


table 2 & 3:- Treatments & Treatments_cut
NOTE:- there are 350 patients right? 280 in treatment table and rest 70 in treatment_cut. that's all the difference b/w these 2 tables.

manual:-
-given_name and surname is in lower_case in these 2 tables. but, in the patient table, the given_name and surname were capitalized (first
letter in uppercase). this could be a problem while merging tables with respect to columns, because then both columns, despite having
same content, are slightly different. (consistency)
-remove u from Auralin and Novadra cols. u is a unit of measurement of dosage but as everything in this col is in same unit, why keep unit? (validity)
-'-' (hyphen) in novadra and Auralin col treated as nan by these people, but by this computer, hyphen is not nan as it holds some value. if
you want the computer to interpret as nan, we need to remove the hyphen. (validity)

automatic:-
-missing values in hba1c_change col (completion)
-1 dupli entry in the name Joseph day (validity)

table 4:- Adverse_reactions
- given_name and surname in lower case (consistency)

ii) MESSY DATA

table 1:- Patients
-contact col contains both phone and email despite being 2 different variables.

table 2 & 3:- Treatments & Treatments_cut
- Auralin and Novadra col should be split into 2 cols, start and end dose. for eg:- right now, under Auralin, its 36u - 39u, which is
start dose and end dose. there should be 2 separate col of auralin, start dose and end dose.
-as both the Treatments_cut is just the continuation of Treatments table, merge them both into one table.

table 4 :- Adverse_reactions
-should not exist independently.






table 3:- adverse_reactions
'''

'\nassessment = finding out errors from the data.\ncleaning = eradicating those errors.\n\nthere are 2 types of assessments:-\n1. manual = you just go through the excel of the dataset, and try to "look" with your naked eyes for any flaws within the dataset\n\n2. automatic = using python built in functions to find the errors in the dataset.\n\nDoing assessment with all the 4 tables:-\n\ni) DIRTY DATA\n\ntable 1:- Patients\n\nmanual:- (what inconsistencies I saw with my eyes)\n-patient with id=9, the name is misspelled as Dsvid whereas in the contact mail, it\'s David (accuracy)\n-In the state column, it sometimes has full form, as New York, and sometimes the abbreviated form being NY denoting the same. (consistency)\n-Zip code of few addresses being 4 digit no, whereas by rule, it should be 5 digit no. (validity)\n\nautomatic:-\nwhen I used .info() built in function:-\n-few col had non null values which were lesser than the rest. it means, there are missing values in this column. data missing for 12 patients\nin address,city, state,zip_code ,country, contact. (completeness)\n-.info() also shows the dtype:-\nsex = obj (string as in male/female) but it uses more memory. instead you can one hot encode to 0 and 1. (validity)\nzip code = float, should have been int (validity)\nbirthdate = obj, should have been datetime (validity)\n-dwhen using .duplicated() , duplicate entries by the name John Doe (validity)\n-when using .describe(), it does mathematical calculations. from the result, min height = 27 inches which ain\'t possible for high bmi. one has\nweight of 48 pounds as 5.2ft height which ain\'t possible. (accuracy)\n\n\ntable 2 & 3:- Treatments & Treatments_cut\nNOTE:- there are 350 patients right? 280 in treatment table and rest 70 in treatment_cut. that\'s all the difference b/w these 2 tables.\n\nmanual:-\n-given_name and surname is in lower_case in these 2 tables. but, in the patient table, the given_name and surname were capitalized (first\nletter in uppercase). this could be a problem while merging tables with respect to columns, because then both columns, despite having\nsame content, are slightly different. (consistency)\n-remove u from Auralin and Novadra cols. u is a unit of measurement of dosage but as everything in this col is in same unit, why keep unit? (validity)\n-\'-\' (hyphen) in novadra and Auralin col treated as nan by these people, but by this computer, hyphen is not nan as it holds some value. if\nyou want the computer to interpret as nan, we need to remove the hyphen. (validity)\n\nautomatic:-\n-missing values in hba1c_change col (completion)\n-1 dupli entry in the name Joseph day (validity)\n\ntable 4:- Adverse_reactions\n- given_name and surname in lower case (consistency)\n\nii) MESSY DATA\n\ntable 1:- Patients\n-contact col contains both phone and email despite being 2 different variables.\n\ntable 2 & 3:- Treatments & Treatments_cut\n- Auralin and Novadra col should be split into 2 cols, start and end dose. for eg:- right now, under Auralin, its 36u - 39u, which is\nstart dose and end dose. there should be 2 separate col of auralin, start dose and end dose.\n-as both the Treatments_cut is just the continuation of Treatments table, merge them both into one table.\n\ntable 4 :- Adverse_reactions\n-should not exist independently.\n\n\n\n\n\n\ntable 3:- adverse_reactions\n'

In [37]:
import numpy as np
import pandas as pd

In [38]:
patients = pd.read_csv("patients.csv")
treatments = pd.read_csv("treatments.csv")
treatments_cut = pd.read_csv("treatments_cut.csv")
adverse_reactions= pd.read_csv("adverse_reactions.csv")

In [39]:
patients.info()

'''
as you can see, col from address to contact, have 12 missing values.
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

'\nas you can see, col from address to contact, have 12 missing values.\n'

In [40]:
patients.duplicated().sum()
'''
no single row where everything from start to end being duplicate entries of some other row.
'''

'\nno single row where everything from start to end being duplicate entries of some other row.\n'

In [41]:
patients.duplicated(subset = ['given_name', 'surname']).sum()
'''
checking duplicate rows by only seing the above 2 columns. if these 2 columns matching, whole row is considered dupli. here, 5 such rows
are dupli.
'''

'\nchecking duplicate rows by only seing the above 2 columns. if these 2 columns matching, whole row is considered dupli. here, 5 such rows\nare dupli.\n'

In [42]:
patients.duplicated(subset = ['given_name', 'surname'])
'''
whichever row is dupli, there will be true associated with it. else, false.
'''

'\nwhichever row is dupli, there will be true associated with it. else, false.\n'

In [43]:
patients[patients.duplicated(subset = ['given_name', 'surname'])]
'''
gives all the rows where true was associated.
'''

'\ngives all the rows where true was associated.\n'

In [44]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [45]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [46]:
treatments.duplicated().sum()
'''
1 dupli row, even without any col in subset, suggesting whole row is dupli of some other row.
'''

'\n1 dupli row, even without any col in subset, suggesting whole row is dupli of some other row.\n'

In [47]:
treatments.duplicated(subset = ['given_name', 'surname']).sum()
'''
the same row as above
'''

'\nthe same row as above\n'

In [48]:
treatments[treatments.duplicated(subset = ['given_name', 'surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [49]:
treatments_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [50]:
treatments_cut.duplicated().sum()

np.int64(0)

In [51]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [52]:
adverse_reactions.duplicated().sum()
'''
no missing values, no duplicates.
'''

'\nno missing values, no duplicates.\n'

### DATA CLEANING

In [53]:
'''
in case of cleaning the dirty data and improving the quality, there are 4 quality dimensions to take care of:-
1. Completeness -> is data missing?
2. Validity -> is data invalid -> negative height -> duplicate patient id
3. Accuracy -> data is valid but not accurate -> weight -> 1kg
4. Consistency -> both valid and accurate but written differently -> New Youk and NY

Data Cleaning order:-

dirty -> Completeness (removing all missing values by either removing rows or filling up empty spaces with some value)
Tidiness (fixing the messy data)
dirty -> Validity (fixing invalid data like -ve height or duplicates, i.e., something which is not possible in real life only is invalid)
dirty -> Accuracy (things that are valid, possible in real life, but, to an extent. 1 kg things exists but one kg grown up human, NOT.)
dirty -> Consistency (Data valid as well as accurate, but written differently, like New York and NY)
'''

'\nin case of cleaning the dirty data and improving the quality, there are 4 quality dimensions to take care of:-\n1. Completeness -> is data missing?\n2. Validity -> is data invalid -> negative height -> duplicate patient id\n3. Accuracy -> data is valid but not accurate -> weight -> 1kg\n4. Consistency -> both valid and accurate but written differently -> New Youk and NY\n\nData Cleaning order:-\n\ndirty -> Completeness (removing all missing values by either removing rows or filling up empty spaces with some value)\nTidiness (fixing the messy data)\ndirty -> Validity (fixing invalid data like -ve height or duplicates, i.e., something which is not possible in real life only is invalid)\ndirty -> Accuracy (things that are valid, possible in real life, but, to an extent. 1 kg things exists but one kg grown up human, NOT.)\ndirty -> Consistency (Data valid as well as accurate, but written differently, like New York and NY)\n'

In [54]:
'''
NOTE:- While CLEANING, never work on the original data. always make a copy.
'''
patients_df = patients.copy()
treatments_df = treatments.copy()
treatments_cut_df = treatments_cut.copy()
adverse_reactions_df = adverse_reactions.copy()

In [55]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

### COMPLETENESS (removing all missing values)

In [56]:
#1. patients table:-
patients_df.fillna('No data',inplace=True)
'''
wherever missing data (na), fill it with 'No data'. this is because in the case of patients, we can't plug in values of address, city, state
zip_code, country, contact of a patient if it is missing. we can't even delete those rows as rest of the patient data is crucial.
'''

<ipython-input-56-bb1663fd8a7c>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No data' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patients_df.fillna('No data',inplace=True)

"\nwherever missing data (na), fill it with 'No data'. this is because in the case of patients, we can't plug in values of address, city, state\nzip_code, country, contact of a patient if it is missing. we can't even delete those rows as rest of the patient data is crucial.\n"

In [57]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

In [58]:
#2. treatments_df and treatments_cut_df.
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [59]:
treatments_df.head()

'''
hba1c change has missing values. but, hba1c change is nothing but change in the hba1c before and after the drug is given. so
hba1c is the diff bw hba1c_start and hba1c_end. this is something which we can put in place of missing values.
'''

'\nhba1c change has missing values. but, hba1c change is nothing but change in the hba1c before and after the drug is given. so\nhba1c is the diff bw hba1c_start and hba1c_end. this is something which we can put in place of missing values.\n'

In [60]:
# as both the tables have same content, it is done for both of them.
treatments_df['hba1c_change'] = treatments_df['hba1c_start'] - treatments_df['hba1c_end']
treatments_cut_df['hba1c_change'] = treatments_cut_df['hba1c_start'] - treatments_cut_df['hba1c_end']

In [61]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [62]:
patients_df.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,LiÃªm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

### TIDINESS (solving problem of messy data)

In [63]:
'''
NOTE:- look in the notes above which I made during assessing to have an idea what's messy.
'''
#1. patients. (contact col where mail and contact number should be in separate col)


def separate(str):
  a = ""
  b = ""
  for ch in str:
    if not ch.isdigit():
      #print(ch)
      if ch != '-' and ch !='(' and ch != ')' and ch != '+':
        #print(ch)
        a=a+ch
      else:
        b=b+ch
    else:
      b=b+ch

  return a,b


str = "PamelaSHill@cuvox.de+1 (217) 569-3204"
separate(str)

('PamelaSHill@cuvox.de  ', '+1(217)569-3204')

In [64]:
patients_df = pd.read_csv("patients.csv", converters={'contact': separate})
patients_df.head()
'''
the string got separated but still, both strings in same col. we need to make 2 diff col for each.
'''

'\nthe string got separated but still, both strings in same col. we need to make 2 diff col for each.\n'

In [65]:
patients_df[['email', 'phone']] = pd.DataFrame(patients_df['contact'].tolist(), index=patients_df.index)
patients_df.head()

'''
when pd.DataFrame(patients_df['contact'].tolist()], it assigns the col name 0 and 1 to the 2 separate strings inside the tuple of the list.
as in, all the strings with email assigned 0 and with phone number assigned 1.
patients_df[['email', 'phone']] creates new col automatically when it is unable to find out the col names specified in this bracket. the col with name 0 becomes email and
col with name 1 becomes phone.
now, you can drop the contact column.
'''

"\nwhen pd.DataFrame(patients_df['contact'].tolist()], it assigns the col name 0 and 1 to the 2 separate strings inside the tuple of the list. \nas in, all the strings with email assigned 0 and with phone number assigned 1.\npatients_df[['email', 'phone']] creates new col automatically when it is unable to find out the col names specified in this bracket. the col with name 0 becomes email and \ncol with name 1 becomes phone. \nnow, you can drop the contact column. \n"

In [66]:
patients_df.drop(columns='contact',inplace=True)

In [67]:
treatments_df = pd.concat([treatments_df,treatments_cut_df])
'''
we joined (concatenated) the 2 tables by stacking them vertically.
'''

'\nwe joined (concatenated) the 2 tables by stacking them vertically. \n'

In [68]:
treatments_df.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrovÃ¡,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [69]:
treatments_df = treatments_df.melt(id_vars=['given_name', 'surname' ,'hba1c_start', 'hba1c_end','hba1c_change'],var_name='type',value_name='dosage_range')

'''
melt function converts the columns which are not specified in id_vars, to row values. the columns in id_vars remain untouched. to the rest of
the columns:- auralin and novodra are not specified, hence, now auralin and novodra which formerly were the column names, are converted to row
values.
NOTE:- all the columns which were not specified, they become the row values of a single column of the name var_name = 'type'. the values of
these former columns, come under value_name = 'dosage_range' where dosage_range becomes the column holding those values.
as in:- taking above table as reference:-
type         dosage_range
auralin       41u-48u
novodra         -
novodra         -
auralin       33u-36u


as you can see, col names become row values. all the col names not specified, go under the single col called type. the values of the old
columns, being auralin and novodra, go under the col called dosage_range.

NOTE:- before, there were 350 patients and hence 350 rows. now there will be double the rows, i.e., 700 rows. first 350 for all the
patients taking auralin and next 350 for all those taking novodra, and the reason being that we have only 1 col for dosage_range and
a patient can't be taking both the drugs at a same time. it can either be auralin or novodra.
'''

'\nmelt function converts the columns which are not specified in id_vars, to row values. the columns in id_vars remain untouched. to the rest of \nthe columns:- \n\n'

In [75]:
treatments_df.head()
'''
problem now is that there will be 2 duplicates of the same patient. one for auralin and one for novodra. he must have dosage_range in either
of these 2 duplicates and - in either of the 2 duplicates.
we need to remove the dupli row containing - in dosage_range.
'''

'\nproblem now is that there will be 2 duplicates of the same patient. one for auralin and one for novodra. he must have dosage_range in either\nof these 2 duplicates and - in either of the 2 duplicates. \nwe need to remove the dupli row containing - in dosage_range. \n'

In [76]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrovÃ¡,7.63,7.20,0.43,auralin,41u - 48u
1,elliot,richardson,7.56,7.09,0.47,auralin,-
2,yukitaka,takenaka,7.68,7.25,0.43,auralin,-
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,alissa,montez,7.78,7.46,0.32,auralin,-
...,...,...,...,...,...,...,...
695,rovzan,kishiev,7.75,7.41,0.34,novodra,-
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
697,bernd,schneider,7.74,7.44,0.30,novodra,-
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u
699,armina,sauvÃ©,7.86,7.40,0.46,novodra,-

In [77]:
treatments_df = treatments_df[treatments_df['dosage_range'] != '-']
'''
taking all the rows where dosage_range is not equal to 1. we get only 350 rows again.
'''

In [78]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrovÃ¡,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woÅºniak,7.76,7.37,0.39,auralin,30u - 36u
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u

In [80]:
#now, we want to split the dosage range into dosage_start and dosage_end.
treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)
treatments_df.drop(columns='dosage_range',inplace=True)

<ipython-input-80-26d1da39a7c8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
<ipython-input-80-26d1da39a7c8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)
<ipython-input-80-26d1da39a7c8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df.drop(columns='dosage_range',inplace=True)

In [81]:
treatments_df
'''
u is uneccesarily there, making values string, occupying more memory. by removing u and making them int, memory efficient.
'''

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrovÃ¡,7.63,7.20,0.43,auralin,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u,38u
9,asia,woÅºniak,7.76,7.37,0.39,auralin,30u,36u
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u,44u

In [83]:
treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u','')
treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u','')

treatments_df['dosage_start'] = treatments_df['dosage_start'].astype('int')
treatments_df['dosage_end'] = treatments_df['dosage_end'].astype('int')

<ipython-input-83-7b92111c8ae3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u','')
<ipython-input-83-7b92111c8ae3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u','')
<ipython-input-83-7b92111c8ae3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start'] = treatments_df['dosage_start'].astype('int')
<ipython-input-83-7b92111c8ae3>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end'] = treatments_df['dosage_end'].astype('int')

In [84]:
#adverse_reaction table should not occur independently and should be merged with treatments_df table.
treatments_df = treatments_df.merge(adverse_reactions_df,on=['given_name','surname'],how='left')

In [85]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrovÃ¡,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woÅºniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [86]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        350 non-null    object
 1   surname           350 non-null    object
 2   hba1c_start       350 non-null    float64
 3   hba1c_end         350 non-null    float64
 4   hba1c_change      350 non-null    float64
 5   type              350 non-null    object
 6   dosage_start      350 non-null    int64
 7   dosage_end        350 non-null    int64
 8   adverse_reaction  35 non-null     object
dtypes: float64(3), int64(2), object(4)
memory usage: 24.7+ KB

In [88]:
  treatments_df['given_name']= treatments_df['given_name'].str.title()
  treatments_df['surname']= treatments_df['surname'].str.title()

In [89]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,JindrovÃ¡,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,Gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,Haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,Archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,WoÅºniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,Christopher,Woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,Maret,Sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,Lixue,Hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,Jakob,Jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,Berta,Napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

### accuracy and validity are only left, fixing of which is yet to be learned.